export const SUPABASE_URL = "https://petvbrlseijabedxaspz.supabase.co";
export const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBldHZicmxzZWlqYWJlZHhhc3B6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI4NjIxNzYsImV4cCI6MjA3ODQzODE3Nn0.bRIv13iu82ukhzY7g5X55oDRiUcGVg0tqcNUvd135xg";
